arial-api:
  player-not-online: "&cPlayer not found."
  format-on: "&econnected to"
  format-off: "&cnot connected &eto"
  message: "&e%target% &eare currently %format% &dArial Client."
  chat:
    enabled: true
    prefix: "&e[&dArial&e]"
    hook: "%arial%"
  list:
    no-players: "&cThere are currently no players online using Arial Client."
    message: "&dArial Client &eusers:"
    list-format: " &e* &f%player%"